### ISSUE TITLE
AMR step size

### ISSUE THREAD

**Issue by GregAbram** [openvkl/openvkl#11] opened 2021-04-28 20:40 UTC
I'm looking at using openVKL to handle AMR volumes in my app.    I've got a little test case  which creates an AMR dataset consisting of three levels, each containing a constant value pi + level#.   It then uses the iteration API to blast a ray though it.   It outer loops through vklIterateInterval and inner loops through the interval's time range using its nominalDeltaT.    It gets the right answers where it samples, demonstrating that its traversing the AMR , but I was expecting a smaller nominalDeltaT where the interval crosses a finer resolution grid.   I had thought this mechanism would enable me to adjust my sampling rate along the ray; as it is, I have no way of discovering what an appropriate sampling rate is.   Shouldn't it be determined by the cellWidth for the current level?

**Comment by gregjohnson** [comment] 2021-04-28 20:59
Hi Greg,

You're using the APIs exactly as intended: the `nominalDeltaT` is meant to represent a minimum cell size you may encounter in that interval (i.e. `cellWidth` here), such that you can perform ray marching, etc. at your own desired sampling rate.

It sounds like you've uncovered a bug, which we'll look into. I'll contact you via email as well about your test case.

Thanks!
Greg

**Comment by gregjohnson** [comment] 2021-05-14 21:37
This should be resolved with v0.13.0, just released. You should have an email from me with tweaks to your test case as well. Let me know if you have any issues.

**Closed by gregjohnson** 2021-05-14 21:37 UTC
